ALTER TABLE "product_vendors" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "product_vendors" CASCADE;--> statement-breakpoint
CREATE INDEX "backorder_fulfillments_backorder_id_idx" ON "backorder_fulfillments" USING btree ("backorder_id");--> statement-breakpoint
CREATE INDEX "backorder_fulfillments_inventory_id_idx" ON "backorder_fulfillments" USING btree ("inventory_id");--> statement-breakpoint
CREATE INDEX "backorders_product_id_idx" ON "backorders" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "backorders_store_id_idx" ON "backorders" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "backorders_sale_item_id_idx" ON "backorders" USING btree ("sale_item_id");--> statement-breakpoint
CREATE INDEX "backorders_active_idx" ON "backorders" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "brands_active_idx" ON "brands" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "categories_active_idx" ON "categories" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "categories_parent_idx" ON "categories" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "customers_active_idx" ON "customers" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "deliveries_customer_id_idx" ON "deliveries" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "deliveries_store_id_idx" ON "deliveries" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "deliveries_sale_id_idx" ON "deliveries" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "deliveries_active_idx" ON "deliveries" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "delivery_items_delivery_id_idx" ON "delivery_items" USING btree ("delivery_id");--> statement-breakpoint
CREATE INDEX "delivery_items_product_id_idx" ON "delivery_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "delivery_items_active_idx" ON "delivery_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "expenses_active_idx" ON "expenses" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "invenotry_product_id_idx" ON "inventory" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "invenotry_store_id_idx" ON "inventory" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "invenotry_is_active_idx" ON "inventory" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "inventory_transactions_product_id_idx" ON "inventory_transactions" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "inventory_transactions_store_id_idx" ON "inventory_transactions" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "inventory_transactions_user_id_idx" ON "inventory_transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "inventory_transactions_inventory_id_idx" ON "inventory_transactions" USING btree ("inventory_id");--> statement-breakpoint
CREATE INDEX "inventory_transactions_reference_id_idx" ON "inventory_transactions" USING btree ("reference_id");--> statement-breakpoint
CREATE INDEX "inventory_transactions_is_active_idx" ON "inventory_transactions" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "product_types_active_idx" ON "product_types" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "products_product_id_idx" ON "products" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "products_category_id_idx" ON "products" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "products_brand_id_idx" ON "products" USING btree ("brand_id");--> statement-breakpoint
CREATE INDEX "products_unit_id_idx" ON "products" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "products_type_id_idx" ON "products" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX "products_is_active_idx" ON "products" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "promissory_note_items_promissory_note_id_idx" ON "promissory_note_items" USING btree ("promissory_note_id");--> statement-breakpoint
CREATE INDEX "promissory_note_items_product_id_idx" ON "promissory_note_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "promissory_note_items_sale_item_id_idx" ON "promissory_note_items" USING btree ("sale_item_id");--> statement-breakpoint
CREATE INDEX "promissory_note_items_active_idx" ON "promissory_note_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "promissory_notes_customer_id_idx" ON "promissory_notes" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "promissory_notes_sale_id_idx" ON "promissory_notes" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "promissory_notes_active_idx" ON "promissory_notes" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "purchase_items_purchase_id_idx" ON "purchase_items" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "purchase_items_product_id_idx" ON "purchase_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "purchase_items_is_active_idx" ON "purchase_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "purchase_order_items_purchase_order_id_idx" ON "purchase_order_items" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "purchase_order_items_product_id_idx" ON "purchase_order_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "purchase_order_items_is_active_idx" ON "purchase_order_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "purchase_orders_vendor_id_idx" ON "purchase_orders" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "purchase_orders_is_active_idx" ON "purchase_orders" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "purchases_vendor_id_idx" ON "purchases" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "purchases_purchase_order_id_idx" ON "purchases" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "purchases_is_active_idx" ON "purchases" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "quotation_items_quotation_id_idx" ON "quotation_items" USING btree ("quotation_id");--> statement-breakpoint
CREATE INDEX "quotation_items_product_id_idx" ON "quotation_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "quotation_items_tax_id_idx" ON "quotation_items" USING btree ("tax_id");--> statement-breakpoint
CREATE INDEX "quotation_items_active_idx" ON "quotation_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "quotations_customer_customer_id_idx" ON "quotations" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "quotations_active_idx" ON "quotations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "receiving_items_inventory_receiving_item_id_idx" ON "receiving_items_inventory" USING btree ("receiving_item_id");--> statement-breakpoint
CREATE INDEX "receiving_items_inventory_is_active_idx" ON "receiving_items_inventory" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "receiving_items_receiving_id_idx" ON "receiving_items" USING btree ("receiving_id");--> statement-breakpoint
CREATE INDEX "receiving_items_product_id_idx" ON "receiving_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "receiving_items_purchase_item_id_idx" ON "receiving_items" USING btree ("purchase_item_id");--> statement-breakpoint
CREATE INDEX "receiving_items_is_active_idx" ON "receiving_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "receiving_purchase_id_idx" ON "receiving" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "receiving_vendor_id_idx" ON "receiving" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "receiving_store_id_idx" ON "receiving" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "receiving_is_active_idx" ON "receiving" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "sale_item_inventory_sale_item_id_idx" ON "sale_item_inventory" USING btree ("sale_item_id");--> statement-breakpoint
CREATE INDEX "sale_item_inventory_inventory_stock_id_idx" ON "sale_item_inventory" USING btree ("inventory_stock_id");--> statement-breakpoint
CREATE INDEX "sale_item_inventory_active_idx" ON "sale_item_inventory" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "sale_items_sale_id_idx" ON "sale_items" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "sale_items_product_id_idx" ON "sale_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "sale_items_store_id_idx" ON "sale_items" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "sale_items_active_idx" ON "sale_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "sale_items_tax_rate_id_idx" ON "sale_items" USING btree ("tax_id");--> statement-breakpoint
CREATE INDEX "sales_customer_id_idx" ON "sales" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "sales_store_id_idx" ON "sales" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "sales_quotation_id_idx" ON "sales" USING btree ("quotation_id");--> statement-breakpoint
CREATE INDEX "sales_active_idx" ON "sales" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "stores_is_active_idx" ON "stores" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "tax_rates_active_idx" ON "tax_rates" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "units_active_idx" ON "units" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "users_active_idx" ON "users" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "vendors_active_idx" ON "vendors" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "waybill_item_inventory_waybill_item_id_idx" ON "waybill_item_inventory" USING btree ("waybill_item_id");--> statement-breakpoint
CREATE INDEX "waybill_item_inventory_inventory_stock_id_idx" ON "waybill_item_inventory" USING btree ("inventory_stock_id");--> statement-breakpoint
CREATE INDEX "waybill_item_inventory_active_idx" ON "waybill_item_inventory" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "waybill_items_product_id_idx" ON "waybill_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "waybill_items_waybill_id_idx" ON "waybill_items" USING btree ("waybill_id");--> statement-breakpoint
CREATE INDEX "waybill_items_sale_item_id_idx" ON "waybill_items" USING btree ("sale_item_id");--> statement-breakpoint
CREATE INDEX "waybill_items_active_idx" ON "waybill_items" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "waybills_customer_id_idx" ON "waybills" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "waybills_store_id_idx" ON "waybills" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "waybills_sale_id_idx" ON "waybills" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "waybills_active_idx" ON "waybills" USING btree ("is_active");